-- Scripts Oracle - cursos-service (EFT S9 Grupo 13)
-- Ejecutar en la Autonomous Database (Oracle Cloud) del esquema de la app.

CREATE TABLE curso (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo          VARCHAR2(50)  NOT NULL UNIQUE,
    nombre          VARCHAR2(200) NOT NULL,
    descripcion     VARCHAR2(1000),
    instructor      VARCHAR2(200) NOT NULL,
    cupos           NUMBER,
    material_s3_key VARCHAR2(500),
    creado_en       TIMESTAMP     NOT NULL
);

CREATE TABLE inscripcion (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    curso_id    NUMBER        NOT NULL,
    estudiante  VARCHAR2(200) NOT NULL,
    fecha       DATE          NOT NULL,
    estado      VARCHAR2(30)  NOT NULL,
    CONSTRAINT uq_inscripcion UNIQUE (curso_id, estudiante),
    CONSTRAINT fk_inscripcion_curso FOREIGN KEY (curso_id) REFERENCES curso (id)
);

CREATE TABLE calificacion (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    curso_id    NUMBER        NOT NULL,
    estudiante  VARCHAR2(200) NOT NULL,
    examen      VARCHAR2(200) NOT NULL,
    nota        NUMBER(3,1)   NOT NULL,
    fecha       DATE          NOT NULL,
    CONSTRAINT fk_calificacion_curso FOREIGN KEY (curso_id) REFERENCES curso (id)
);
